 Student Attendance Analytics using Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("subdata_pandas/CSEB_Attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0%,Critical,36 more,Never,12
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0

#### Section 1: Data Inspection

In [3]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
df.head(10)

df.shape

df.dtypes

Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [4]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
df.isna()
df.isna().sum()

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

In [5]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
df.rename(columns={
    "Roll No": "roll_no",
    "Student Name": "student_name",
    "Attendance %": "attendance_pct"
}, inplace=True)
df

,roll_no,student_name,Subject,Total Classes,Present,Absent,Excused,attendance_pct,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0%,Critical,36 more,Never,12
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0

In [7]:
# Q4. Convert Attendance % from string format to numeric float

# Convert attendance percentage from string to float
raw_attendance = df["attendance_pct"]

has_percent_sign = raw_attendance.astype("string").str.contains(
    "%", na=False
)

attendance_values = pd.to_numeric(
    raw_attendance.astype("string").str.replace("%", "", regex=False),
    errors="coerce"
).astype("float64")

# Convert percentage strings or numeric values above 1
df["attendance_pct"] = attendance_values.where(
    ~(has_percent_sign | (attendance_values > 1)),
    attendance_values / 100
).astype("float64")


# Convert Last Present Date to datetime, handling "Never" as NaT
df["last_present_date"] = pd.to_datetime(
    df["Last Present Date"].replace("Never", pd.NaT),
    errors="coerce"
)


# Display the converted columns
display(df[["attendance_pct", "last_present_date"]].head())

   attendance_pct last_present_date
0            1.00        2026-10-09
1            1.00        2026-10-09
2            1.00        2026-10-09
3            0.92        2026-10-09
4            0.92        2026-10-09

#### Section 2: Filtering & Selection

In [8]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
critical_students = df[df["Status"] == "Critical"].sort_values(
    by="attendance_pct",
    ascending=True
)

In [9]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
fully_absent = df[df["Present"] == 0]

# Display roll number, name, and consecutive absences
display(fully_absent[[
    "roll_no",
    "student_name",
    "Consecutive Absences"
]])

       roll_no     student_name  Consecutive Absences
10  4MW24CS071       LAXMEESH V                    12
63  4MW25CS405  MANYA PRARTHANA                    12

In [10]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """

df.loc[df["Status"] == "Safe"]
df.iloc[:15, 1:6]

,student_name,Subject,Total Classes,Present,Absent
0,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
1,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
2,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
3,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1
4,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1
5,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11
6,KRITHI,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
7,KRITHIKA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
8,LAKSHMI,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
9,LAVANYA SHANKAR MOGER,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2
10,LAXMEESH V,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12
11,LIKHITA S,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0
12,LIPIKA NAYAK,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1
13,MAHALINGAPPA C,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11
14,MANASA R KULAL,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0

In [11]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
absent_students = df[df["Consecutive Absences"] >= 5]

# Display name, status, and last present date
display(absent_students[[
    "student_name",
    "Status",
    "Last Present Date"
]])

       student_name    Status Last Present Date
5        KOUSHTUBHA  Critical        2026-09-18
10       LAXMEESH V  Critical             Never
35    NITHIL SHETTY  Critical        2026-09-18
46  PRATHAM G KUMAR  Critical        2026-09-18
49       PRATHWEESH  Critical        2026-09-18
63  MANYA PRARTHANA  Critical             Never

### Section 3: Grouping & Aggregation

In [12]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
# Group by Status and calculate the required statistics
summary = df.groupby("Status").agg(
    student_count=("Status", "count"),
    average_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("Consecutive Absences", "max")
)

display(summary)

          student_count  average_attendance  max_consecutive_absences
Status
Critical              9            0.173333                        12
Safe                 42            0.969524                         0
Warning              14            0.807143                         1

In [13]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""

conditions = [
    df["attendance_pct"] >= 0.90,
    (df["attendance_pct"] >= 0.75) & (df["attendance_pct"] < 0.90),
    (df["attendance_pct"] >= 0.60) & (df["attendance_pct"] < 0.75),
    df["attendance_pct"] < 0.60
]

# Define category names
categories = ["Excellent", "Good", "Average", "Poor"]

# Create the new column
df["Attendance Category"] = np.select(conditions, categories, default="Unknown")

# Count students in each category
display(df.groupby("Attendance Category").size())

Attendance Category
Excellent    42
Good         14
Poor          9
dtype: int64

In [14]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
df[["Total Classes", "Present", "Absent"]].agg("sum")

Total Classes    780
Present          643
Absent           137
dtype: int64

In [15]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
# Group by Status and calculate the required statistics
result = df.groupby("Status").agg(
    Present_min=("Present", "min"),
    Present_max=("Present", "max"),
    Present_mean=("Present", "mean"),
    Absent_sum=("Absent", "sum")
)

display(result)

          Present_min  Present_max  Present_mean  Absent_sum
Status
Critical            0            7      2.111111          89
Safe               11           12     11.619048          16
Warning             9           10      9.714286          32

### Section 4: Feature Engineering & Transformation

In [16]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
# Create Risk Score column
df["Risk Score"] = (
    df["Absent"] * 0.4
    + df["Consecutive Absences"] * 0.6
)

# Display the top 10 students with the highest risk score
display(
    df.sort_values(by="Risk Score", ascending=False)
      .head(10)
)

,roll_no,student_name,Subject,Total Classes,Present,Absent,Excused,attendance_pct,Status,Classes Needed (75%),Last Present Date,Consecutive Absences,last_present_date,Attendance Category,Risk Score
10,4MW24CS071,LAXMEESH V,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,Never,12,NaT,Poor,12.0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,Never,12,NaT,Poor,12.0
46,4MW24CS107,PRATHAM G KUMAR,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4
35,4MW24CS096,NITHIL SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4
5,4MW24CS066,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4
49,4MW24CS110,PRATHWEESH,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4
13,4MW24CS074,MAHALINGAPPA C,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-22,4,2026-09-22,Poor,6.8
51,4MW24CS112,RAHUL,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-09-29,2,2026-09-29,Poor,3.2
29,4MW24CS090,NIKHIL NAIK,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-10-09,0,2026-10-09,Poor,2.0
33,4MW24CS094,NISHA M B,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-06,1,2026-10-06,Good,1.4

In [17]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
# Extract the numeric value from Classes Needed (75%)
df["Classes Needed (Numeric)"] = (
    df["Classes Needed (75%)"]
    .str.extract(r"(\d+)")
    .fillna(0)
    .astype(int)
)

display(df[["Classes Needed (75%)", "Classes Needed (Numeric)"]].head())

  Classes Needed (75%)  Classes Needed (Numeric)
0                ✓ Met                         0
1                ✓ Met                         0
2                ✓ Met                         0
3                ✓ Met                         0
4                ✓ Met                         0

In [18]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
# Create Attendance Flag using apply() and lambda
df["Attendance Flag"] = df["attendance_pct"].apply(
    lambda x: "Defaulter" if x < 0.75 else "Safe"
)

display(df[["attendance_pct", "Attendance Flag"]].head())

   attendance_pct Attendance Flag
0            1.00            Safe
1            1.00            Safe
2            1.00            Safe
3            0.92            Safe
4            0.92            Safe

In [19]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
bins = [0, 50, 75, 90, 100]
labels = ["Critical", "Warning", "Good", "Excellent"]

# Create attendance ranges
df["Attendance Range"] = pd.cut(
    df["attendance_pct"] * 100,
    bins=bins,
    labels=labels,
    include_lowest=True
)
df

,roll_no,student_name,Subject,Total Classes,Present,Absent,Excused,attendance_pct,Status,Classes Needed (75%),Last Present Date,Consecutive Absences,last_present_date,Attendance Category,Risk Score,Classes Needed (Numeric),Attendance Flag,Attendance Range
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.0,0,Safe,Excellent
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.0,0,Safe,Excellent
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.0,0,Safe,Excellent
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.4,0,Safe,Excellent
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.4,0,Safe,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,2026-10-09,Good,0.8,0,Safe,Good
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.4,0,Safe,Excellent
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.4,0,Safe,Excellent
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,Never,12,NaT,Poor,12.0,36,Defaulter,Critical
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,2026-10-09,Good,0.8,0,Safe,Good

### Section 5: Advanced Analysis

In [20]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
# Create a pivot table showing student counts
summary = pd.pivot_table(
    df,
    index="Status",
    columns="Attendance Category",
    aggfunc="size",
    fill_value=0
)

display(summary)

Attendance Category  Excellent  Good  Poor
Status
Critical                     0     0     9
Safe                        42     0     0
Warning                      0    14     0

In [21]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
# Extract the base name (remove extra spaces and trailing numbers/suffixes if present)
df["base_name"] = (
    df["student_name"]
    .str.strip()
    .str.extract(r"^([A-Za-z]+)")[0]
    .str.upper()
)

# Identify all rows where the base name repeats
duplicates = df[
    df["base_name"].duplicated(keep=False)
].sort_values(by="base_name")

df

,roll_no,student_name,Subject,Total Classes,Present,Absent,Excused,attendance_pct,Status,Classes Needed (75%),Last Present Date,Consecutive Absences,last_present_date,Attendance Category,Risk Score,Classes Needed (Numeric),Attendance Flag,Attendance Range,base_name
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.0,0,Safe,Excellent,KAVYA
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.0,0,Safe,Excellent,KEERTHANA
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.0,0,Safe,Excellent,KEERTHI
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.4,0,Safe,Excellent,KHUSHI
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.4,0,Safe,Excellent,KISHAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,2026-10-09,Good,0.8,0,Safe,Good,SAHANA
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.4,0,Safe,Excellent,SAKSHI
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,2026-10-09,Excellent,0.4,0,Safe,Excellent,MANISH
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,Never,12,NaT,Poor,12.0,36,Defaulter,Critical,MANYA
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,2026-10-09,Good,0.8,0,Safe,Good,ROHAN

In [22]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
student_details = pd.DataFrame({
    "Roll No": [101, 102, 103, 104, 105],
    "Branch": ["CSE", "ISE", "CSE", "ECE", "AIML"],
    "Semester": [5, 5, 5, 5, 5]
})

# Perform an inner join
student_details = student_details.rename(columns={"Roll No": "roll_no"})

student_details["roll_no"] = df["roll_no"].head(len(student_details)).to_numpy()

merged_df = pd.merge(
    df,
    student_details,
    on="roll_no",
    how="inner"
)

display(merged_df)

,roll_no,student_name,Subject,Total Classes,Present,Absent,Excused,attendance_pct,Status,Classes Needed (75%),...,Consecutive Absences,last_present_date,Attendance Category,Risk Score,Classes Needed (Numeric),Attendance Flag,Attendance Range,base_name,Branch,Semester
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,...,0,2026-10-09,Excellent,0.0,0,Safe,Excellent,KAVYA,CSE,5
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,...,0,2026-10-09,Excellent,0.0,0,Safe,Excellent,KEERTHANA,ISE,5
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,...,0,2026-10-09,Excellent,0.0,0,Safe,Excellent,KEERTHI,CSE,5
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,...,0,2026-10-09,Excellent,0.4,0,Safe,Excellent,KHUSHI,ECE,5
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,...,0,2026-10-09,Excellent,0.4,0,Safe,Excellent,KISHAN,AIML,5

In [25]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#a
critical_students = df[df["Status"] == "Critical"]
critical_students.to_csv("critical_students.csv", index=False)

#b
status_summary = df.groupby("Status").agg({
    "Present": ["min", "max", "mean"],
    "Absent": "sum",
    "Total Classes": "sum"
})
status_summary.to_csv("status_summary.csv")

#c
top_10_risk = df.sort_values(
    by="Risk Score",
    ascending=False
).head(10)

top_10_risk.to_csv("top_10_risk_score.csv", index=False)
#display all outputs
display(critical_students)
display(status_summary)
display(top_10_risk)

,roll_no,student_name,Subject,Total Classes,Present,Absent,Excused,attendance_pct,Status,Classes Needed (75%),Last Present Date,Consecutive Absences,last_present_date,Attendance Category,Risk Score,Classes Needed (Numeric),Attendance Flag,Attendance Range,base_name
5,4MW24CS066,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4,32,Defaulter,Critical,KOUSHTUBHA
10,4MW24CS071,LAXMEESH V,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,Never,12,NaT,Poor,12.0,36,Defaulter,Critical,LAXMEESH
13,4MW24CS074,MAHALINGAPPA C,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-22,4,2026-09-22,Poor,6.8,32,Defaulter,Critical,MAHALINGAPPA
29,4MW24CS090,NIKHIL NAIK,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-10-09,0,2026-10-09,Poor,2.0,8,Defaulter,Warning,NIKHIL
35,4MW24CS096,NITHIL SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4,32,Defaulter,Critical,NITHIL
46,4MW24CS107,PRATHAM G KUMAR,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4,32,Defaulter,Critical,PRATHAM
49,4MW24CS110,PRATHWEESH,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4,32,Defaulter,Critical,PRATHWEESH
51,4MW24CS112,RAHUL,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-09-29,2,2026-09-29,Poor,3.2,8,Defaulter,Warning,RAHUL
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,Never,12,NaT,Poor,12.0,36,Defaulter,Critical,MANYA

         Present                Absent Total Classes
             min max       mean    sum           sum
Status
Critical       0   7   2.111111     89           108
Safe          11  12  11.619048     16           504
Warning        9  10   9.714286     32           168

,roll_no,student_name,Subject,Total Classes,Present,Absent,Excused,attendance_pct,Status,Classes Needed (75%),Last Present Date,Consecutive Absences,last_present_date,Attendance Category,Risk Score,Classes Needed (Numeric),Attendance Flag,Attendance Range,base_name
10,4MW24CS071,LAXMEESH V,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,Never,12,NaT,Poor,12.0,36,Defaulter,Critical,LAXMEESH
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,Never,12,NaT,Poor,12.0,36,Defaulter,Critical,MANYA
46,4MW24CS107,PRATHAM G KUMAR,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4,32,Defaulter,Critical,PRATHAM
35,4MW24CS096,NITHIL SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4,32,Defaulter,Critical,NITHIL
5,4MW24CS066,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4,32,Defaulter,Critical,KOUSHTUBHA
49,4MW24CS110,PRATHWEESH,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5,2026-09-18,Poor,7.4,32,Defaulter,Critical,PRATHWEESH
13,4MW24CS074,MAHALINGAPPA C,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-22,4,2026-09-22,Poor,6.8,32,Defaulter,Critical,MAHALINGAPPA
51,4MW24CS112,RAHUL,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-09-29,2,2026-09-29,Poor,3.2,8,Defaulter,Warning,RAHUL
29,4MW24CS090,NIKHIL NAIK,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-10-09,0,2026-10-09,Poor,2.0,8,Defaulter,Warning,NIKHIL
33,4MW24CS094,NISHA M B,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-06,1,2026-10-06,Good,1.4,0,Safe,Good,NISHA